# AAAI ICWSM 2024 | Tutorial | June 3rd | 2-6pm
## <u>Collectivist and Perspectivist Approaches to Studying Online Toxicity</u>
### Yotam Shmargad, School of Government & Public Policy, University of Arizona

#### This is the <b>first</b> of two notebooks we will discuss during the tutorial. The notebook is written in Python and walks participants through analyzing YouTube comments from a *Collectivist* approach. The notebook:
1.   Collects YouTube videos for <b>two</b> separate queries
2.   Collects a set of comments for the videos from each query
3.   Analyzes *hatefulness* in the two sets of comments
4.   Compares the average hatefulness in the two sets *(descriptive norm)*
5.   Compares the association between hatefulness and like counts in the two sets *(injunctive norm)*

### 1. Collect YouTube videos for <b>two</b> separate queries`

In [1]:
# Install library for YouTube data collection https://youtube-data-api.readthedocs.io/en/latest/youtube_api.html
!pip install youtube-data-api

Collecting youtube-data-api
  Downloading youtube_data_api-0.0.21-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from youtube-data-api) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from youtube-data-api) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->youtube-data-api) (1.17.0)
Downloading youtube_data_api-0.0.21-py3-none-any.whl (12 kB)
Installing collected packages: youtube-data-api
Successfully installed youtube-data-api-0.0.21

In [2]:
# Import libraries for data collection, management, and analysis
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from youtube_api import YouTubeDataAPI
import statsmodels.api as sm

In [3]:
# Obtain API Key from https://console.cloud.google.com/apis/
# Authenticate with YouTube - place the API Key you obtained between the quotes
yt = YouTubeDataAPI("AIzaSyAVo4MveZjFV8O7-cYczq5dHS-Est2qJww")

In [4]:
# Collect 50 videos using a query search - place your search term between the quotes
vids1 = yt.search("ChatGPT",max_results = 50)

In [5]:
# Collect 50 videos using a different query
vids2 = yt.search("Claude",max_results = 50)

In [6]:
# Print number of videos collected for each query
print("Query 1:",len(vids1))
print("Query 2:",len(vids2))

Query 1: 50
Query 2: 50

In [12]:
# Retrieve information for the first video in the first query
vids1[0]

{'video_id': 'Gaf_jCnA6mc',
 'channel_title': 'Charlie Chang',
 'channel_id': 'UCTQuKo8v0PaPCvk5aRxc_Yg',
 'video_publish_date': 1680631793.0,
 'video_title': 'ChatGPT Tutorial: How to Use Chat GPT For Beginners',
 'video_description': 'Get up to 75% off your hosting (only $2.99/mo) + 3 months FREE with Hostinger: https://www.charliechang.com/hostinger/ ^Use ...',
 'video_category': None,
 'video_thumbnail': 'https://i.ytimg.com/vi/Gaf_jCnA6mc/hqdefault.jpg',
 'collection_date': datetime.datetime(2026, 4, 9, 17, 8, 26, 872375)}

In [13]:
# Retrieve Video ID information for the first video in the first query
vids1[0]['video_id']

'Gaf_jCnA6mc'

In [9]:
# Place video data into pandas tables
vids1_df = pd.DataFrame(vids1)
vids2_df = pd.DataFrame(vids2)

In [10]:
# Print table for videos from first query
vids1_df

,video_id,channel_title,channel_id,video_publish_date,video_title,video_description,video_category,video_thumbnail,collection_date
0,Gaf_jCnA6mc,Charlie Chang,UCTQuKo8v0PaPCvk5aRxc_Yg,1.680632e+09,ChatGPT Tutorial: How to Use Chat GPT For Begi...,Get up to 75% off your hosting (only $2.99/mo)...,None,https://i.ytimg.com/vi/Gaf_jCnA6mc/hqdefault.jpg,2026-04-09 17:08:26.872375
1,7zPQV1BSH_k,Dan Martell,UCA-mWX9CvCTVFWRMb9bKc9w,1.760717e+09,23 Ways to Use ChatGPT So Well it Feels Like C...,Want the prompt I use to write books like this...,None,https://i.ytimg.com/vi/7zPQV1BSH_k/hqdefault.jpg,2026-04-09 17:08:26.872402
2,l4zRU5n-PNo,SURESAM,UCrfMwUYrOBWN8S65YF2tgnw,1.760100e+09,എന്താണീ Chat GPT? അത് എങ്ങിനെ ഉപയോഗിക്കാം?!,എന്താണീ Chat GPT? അത് എങ്ങിനെ ഉപയോഗിക്കാം?! Ho...,None,https://i.ytimg.com/vi/l4zRU5n-PNo/hqdefault.jpg,2026-04-09 17:08:26.872419
3,czwzYb-y138,Negócios em Mente,UCnnBpJ_fjSfS2BdNJce8UBw,1.770649e+09,"Curso de ChatGPT 2026 | GRÁTIS, ATUALIZADO e C...",10X MAIS PRODUTIVO - Gestão de tarefas e pro...,None,https://i.ytimg.com/vi/czwzYb-y138/hqdefault.jpg,2026-04-09 17:08:26.872434
4,loujaeBy8p0,theMITmonk,UC4ZVkG3RQPzvZk7alIVjcCg,1.771425e+09,5 Hacks To Use ChatGPT So Well It’s Almost Unfair,"In this video, I break down how I use ChatGPT,...",None,https://i.ytimg.com/vi/loujaeBy8p0/hqdefault.jpg,2026-04-09 17:08:26.872449
5,hOe0maWOhp8,AI Mastermind,UCYqDOCjRMttt5jLz5sLuCPQ,1.735748e+09,ChatGPT for Beginners - 2026 Edition,"In this video, Tony DeSimone simplifies the pr...",None,https://i.ytimg.com/vi/hOe0maWOhp8/hqdefault.jpg,2026-04-09 17:08:26.872462
6,AXn2XVLf7d0,The AI Advantage,UCHhYXsLBEVVnbvsq57n1MTQ,1.670537e+09,How To Use ChatGPT by OpenAI For Beginners,Subscribe to the channel for more beginner con...,None,https://i.ytimg.com/vi/AXn2XVLf7d0/hqdefault.jpg,2026-04-09 17:08:26.872475
7,JXSm8A-E6gM,Genius Manu,UCglO7skDoAQG8Lsg_QOgiZw,1.775419e+09,"Google lanzó Gemma 4, un ChatGPT pero GRATIS, ...","Te hablo de Gemma 4, un Nuevo modelo de Google...",None,https://i.ytimg.com/vi/JXSm8A-E6gM/hqdefault.jpg,2026-04-09 17:08:26.872487
8,kvU0fe2Ly-s,Knotora,UCgAK78JdA5XCnDo07p01XSA,1.750613e+09,CHATGPT gender reveal!,chatgpt #ai #aichatbots #aicomedy #characterai...,None,https://i.ytimg.com/vi/kvU0fe2Ly-s/hqdefault.jpg,2026-04-09 17:08:26.872500
9,qCMVHfIYY7k,Adrián Sáenz,UCVt4ugq2txl_szlXAO7B3-g,1.768840e+09,Estos Hacks De ChatGPT Te Harán Tan Productivo...,Curso: https://youtu.be/Phal-sPAunk Índice 00:...,None,https://i.ytimg.com/vi/qCMVHfIYY7k/hqdefault.jpg,2026-04-09 17:08:26.872512
10,Xm7ySx8VJXo,TechSimplify,UCJjZJtj-EF-Jg8zKbO-12Bg,1.760702e+09,ChatGPT vs Gemini – AI Image Generation Test (...,Who's the real AI image champion — ChatGPT or ...,None,https://i.ytimg.com/vi/Xm7ySx8VJXo/hqdefault.jpg,2026-04-09 17:08:26.872524
11,1TWpaGgnpjI,Sunday Cool,UCGo0VEAAJW0o0FZdQ-wmTmQ,1.753052e+09,Terrifying conversation with ChatGPT 👀 #ninjas...,,None,https://i.ytimg.com/vi/1TWpaGgnpjI/hqdefault.jpg,2026-04-09 17:08:26.872537
12,hptchvNnsoI,teddywang86,UC_mTME_0z6pEteDMRUUwKlA,1.748401e+09,"ChatGPT, Show Me Rice",,None,https://i.ytimg.com/vi/hptchvNnsoI/hqdefault.jpg,2026-04-09 17:08:26.872549
13,XRU-CjzYt_o,Dan Martell,UCA-mWX9CvCTVFWRMb9bKc9w,1.775135e+09,Why I Switched From ChatGPT to Claude (without...,Get your FREE AI Prompt Cheatsheet here: https...,None,https://i.ytimg.com/vi/XRU-CjzYt_o/hqdefault.jpg,2026-04-09 17:08:26.872561
14,nn29T4yPc8E,Jay Shetty Podcast,UCbk_QsfaFZG6PdQeCvaYXJQ,1.774012e+09,How To Use Chat GPT to Actually Change Your Life,"Today, Jay invites us to reconsider something ...",None,https://i.ytimg.com/vi/nn29T4yPc8E/hqdefault.jpg,2026-04-09 17:08:26.872573
15,TwPFDbuBLcc,Helen Christie,UCWajepQsMCmNBUHVIPirk8g,1.722442e+09,nobody: ChatGPT,comedy #funnyvideo #chatgpt #ai #robot.,None,https://i.ytimg.com/vi/TwPFDbuBLcc/hqdefault.jpg,2026-04-09 17:08:26.872585
16,OxuQrCpMnjI,AFR Technology,UCZff6I2okeH71I5jsE0LirQ,1.760883e+09,Chatgpt কিভাবে ব্যবহার করব | Chatgpt Full Cour...,"chatgpt কিভাবে ব্যবহার করব বাংলা,chatgpt kivab...",None,https://i.ytimg.com/vi/OxuQrCpMnjI/hqdefault.jpg,2026-04-09 17:08:26.872597
17,HyoQLw8W0lg,Hindi Tutorials,UCKa6ggkkUn-fsUiUmbib1Tg,1.771080e+09,ChatGPT kaise use kare | How to Use ChatGPT | ...,"Hello, Dosto es video me maine apko bataya hai...",None,https://i.ytimg.com/vi/HyoQLw8W0lg/hqdefault.jpg,2026-04-09 17:08:26.872608
18,kX_p3r2eLwY,Manish4u,UC3m2kLQNIPUqebFAHNfbcAA,1.769282e+09,chatgpt kaise use kare - chatgpt how to use,"manish4u Hello & Namaste Everyone, chatgpt kai...",None,https://i.ytimg.com/vi/kX_p3r2eLwY/hqdefault.jpg,2026-04-09 17:08:26.872620
19,73ZaWJnrApQ,Austin B. Chen,UCZRzbHVezKH-SJxQ8e3YM5w,1.758161e+09,i actually counted... drop your guess ⬇️ #pian...,try to beat chatgpt: how many notes did you he...,None,https://i.ytimg.com/vi/73ZaWJnrApQ/hqdefault.jpg,2026-04-09 17:08:26.872632
20,zJL9K3xscRo,Smart Tech For Any Age,UCK1wTf_JLCq-wpT65xwNt8A,1.756041e+09,ChatGPT Tutorial 2025 for Seniors and Beginner...,DOWNLOAD YOUR FREE GUIDE Getting Started with ...,None,https://i.ytimg.com/vi/zJL9K3xscRo/hqdefault.jpg,2026-04-09 17:08:26.872643
21,tuWg591XYjE,looser tech,UC02Bsu5w84GthToljSrjl4Q,1.751127e+09,Viral Chatgpt Ai Prompt Se Photo kaise banaye ...,Viral Chatgpt Ai Prompt Se Photo kaise banaye ...,None,https://i.ytimg.com/vi/tuWg591XYjE/hqdefault.jpg,2026-04-09 17:08:26.872655
22,3jweqQHJ5rg,Vjphotoholic,UC41Z1AkPP9Ujk_eoV35YI6Q,1.750144e+09,Chatgpt image generator prompt tutorial part 2...,Chatgpt image generator prompt tutorial part 2...,None,https://i.ytimg.com/vi/3jweqQHJ5rg/hqdefault.jpg,2026-04-09 17:08:26.872666
23,WJPDqAzN1X8,ZAMONUZ,UCL8U-WhAm_bfiJ40SkWM6aw,1.756466e+09,ChatGPT 16 yoshli yigit o’limiga sabab bo’ldi,,None,https://i.ytimg.com/vi/WJPDqAzN1X8/hqdefault.jpg,2026-04-09 17:08:26.872678
24,YAzLh7eOSrk,Saturday Night Live,UCqFzWxSCi39LnW1JKFR3efg,1.759645e+09,ChatGPTío - SNL,A commercial advertises a more authentic versi...,None,https://i.ytimg.com/vi/YAzLh7eOSrk/hqdefault.jpg,2026-04-09 17:08:26.872690
25,VK5mm8JUUJQ,Viral Khan Sir,UCBDLC4K2ZIUzfuEYno_U6-Q,1.686222e+09,Chat GPT के बारे में खान सर ने ये क्या कह दिया...,,None,https://i.ytimg.com/vi/VK5mm8JUUJQ/hqdefault.jpg,2026-04-09 17:08:26.872702
26,3aLZ0YwP5so,ChatGPT Empire (বাংলা),UCApl_8LpBxiK269-VrCZynw,1.732022e+09,ChatGPT স্মার্টফোনে কিভাবে চালাবেন? Chat GPT T...,আপনার স্মার্টফোনে ChatGPT ব্যবহার করা এখন অনেক...,None,https://i.ytimg.com/vi/3aLZ0YwP5so/hqdefault.jpg,2026-04-09 17:08:26.872714
27,3u1k7Jyn434,Valeria Digital,UCKmHeBkUWPDgnItiDXDbX0g,1.717438e+09,Tutorial ChatGPT ¿Qué es ChatGPT y cómo funciona?,"En este Tutorial rápido en español, te voy a e...",None,https://i.ytimg.com/vi/3u1k7Jyn434/hqdefault.jpg,2026-04-09 17:08:26.872726
28,BAfaKsRViZ4,Tech Boss,UCnKhQkCUS1oCEvjuTfU4xIw,1.735732e+09,🔥 இப்போ WhatsAppலே ChatGPT😁,Media Partner : Adada Creators Email : techbos...,None,https://i.ytimg.com/vi/BAfaKsRViZ4/hqdefault.jpg,2026-04-09 17:08:26.872737
29,cyc1Mr-g6Zk,MNtechwork,UCC4zOvIoVClBZtykyB2eoNw,1.739203e+09,How to Install ChatGPT on Android | How to Dow...,how to fix in this video we show you how to si...,None,https://i.ytimg.com/vi/cyc1Mr-g6Zk/hqdefault.jpg,2026-04-09 17:08:26.872748
30,ni9-li6IptI,MANIIISH,UCdsvm_Oi2ctZUE_HbHx1MbQ,1.752943e+09,Viral Chatgpt Photo Editing! 🔥 Ai trend Prompt...,Ai Se Cinematic Photo Kaise Banaye! Viral Pro...,None,https://i.ytimg.com/vi/ni9-li6IptI/hqdefault.jpg,2026-04-09 17:08:26.872760
31,0rqh5ySV25c,VisualEconomik,UC5HdVtarytnZi4eLogHAfoQ,1.775485e+09,El imperio de ChatGPT se derrumba: ¿Puede QUEB...,El 12 de Abril presentamos el Máster en IA apl...,None,https://i.ytimg.com/vi/0rqh5ySV25c/hqdefault.jpg,2026-04-09 17:08:26.872771
32,f2mRAGvKca8,Samim Jerry,UCem-E8Np-uuR38DcBuRCHVw,1.673965e+09,How To Use ChatGPT in Bengali - কিভাবে ChatGPT...,How To Use Chat GPT in Bengali - কিভাবে ChatGP...,None,https://i.ytimg.com/vi/f2mRAGvKca8/hqdefault.jpg,2026-04-09 17:08:26.872783
33,vwEFXXajePs,Goygoy Mizah,UCx0BRvgvmHrLu3jG5yb5xrw,1.755163e+09,"ChatGPT’yi Kandırmaya Çalıştı, Sonuç Efsane! 🤯😂",Arkadaş “Ne yazarsam tersini yaz” diyerek Chat...,None,https://i.ytimg.com/vi/vwEFXXajePs/hqdefault.jpg,2026-04-09 17:08:26.872794
34,kHWyJ-baLnE,Zdak,UC_485Ao_SxlCaBlOZORVsVQ,1.735131e+09,ChatGPT is savage ☠️,"ChatGPT cooked bro, fr Funny Chat GPT conversa...",None,https://i.ytimg.com/vi/kHWyJ-baLnE/hqdefault.jpg,2026-04-09 17:08:26.872806
35,GIPlnfHQcz0,The AI Advantage,UCHhYXsLBEVVnbvsq57n1MTQ,1.775241e+09,Every New ChatGPT Feature Explained &amp; More...,Subscribe for more weekly breakdowns on the AI...,None,https://i.ytimg.com/vi/GIPlnfHQcz0/hqdefault.jpg,2026-04-09 17:08:26.872817
36,Zagpt1JHLUI,Kevin Stratvert,UCfJT_eYDTmDE-ovKaxVE1ig,1.746212e+09,7 Mind-Blowing ChatGPT Features You&#39;re Not...,New to ChatGPT or want a quick intro? Start he...,None,https://i.ytimg.com/vi/Zagpt1JHLUI/hqdefault.jpg,2026-04-09 17:08:26.872828
37,4j0Ky_diI44,Xataka,UCUrYBZGlEOSD1_ds_HcNd6A,1.683314e+09,CÓMO UTILIZAR CHAT GPT EN TU MÓVIL 🤖 #shorts,Suscríbete a nuestro canal https://bit.ly/3iFH...,None,https://i.ytimg.com/vi/4j0Ky_diI44/hqdefault.jpg,2026-04-09 17:08:26.872840
38,RHRisfGECi0,Be Inspired,UCaKZDEMDdQc8t6GzFj1_TDw,1.756046e+09,Viral ChatGPT Conversation Left Millions Speec...,This is crazy!!! Watch the original conversati...,None,https://i.ytimg.com/vi/RHRisfGECi0/hqdefault.jpg,2026-04-09 17:08:26.872851
39,miVkJmaVv-g,AceHype,UC8JDsefCLwWkzvdVPjtODtA,1.754191e+09,Confessing M*rder To ChatGPT🤯,source:@jumpersjump.,None,https://i.ytimg.com/vi/miVkJmaVv-g/hqdefault.jpg,2026-04-09 17:08:26.872863
40,eXA3fVaNuLo,GK IQ Loksewa Plus,UC0qnAptHrU7IMzSpjwUPnhw,1.705716e+09,ChatGPT kasari chalaune | chatgpt kasari use g...,chatgpt chatgpt kasari chaunaune chatgpt kasar...,None,https://i.ytimg.com/vi/eXA3fVaNuLo/hqdefault.jpg,2026-04-09 17:08:26.872874
41,lycW9qF0lo0,Bestan guide,UCftiaJYW94_HgfvSRwRLGKA,1.774512e+09,Chatgpt kaise use kare - Chatgpt how to use | ...,Chatgpt kaise use kare - Chatgpt how to use | ...,None,https://i.ytimg.com/vi/lycW9qF0lo0/hqdefault.jpg,2026-04-09 17:08:26.872886
42,n_uCSpQmJkY,Ai Pro Mind,UCNsS5xEmVcFZOl90ojSJnYg,1.753620e+09,Chatgpt Ai couple photo Editing prompt | Gemin...,Chatgpt Photo Editing Prompt | Trending photo ...,None,https://i.ytimg.com/vi/n_uCSpQmJkY/hqdefault.jpg,2026-04-09 17:08:26.872898
43,VRjgNgJms3Q,Eddy Burback,UCuo9VyowIT-ljA5G2ZuC6Yw,1.761840e+09,ChatGPT made me delusional,Try for FREE or unlock more features with prem...,None,https://i.ytimg.com/vi/VRjgNgJms3Q/hqdefault.jpg,2026-04-09 17:08:26.872915
44,nlXOQxPP5sQ,Humsafar Tech,UC7YHgndkMslP_xCOD2LtBXg,1.772248e+09,ChatGPT Kaise Use Kare | How to Use ChatGPT AI...,ChatGPT Kaise Use Kare? Is video me maine step...,None,https://i.ytimg.com/vi/nlXOQxPP5sQ/hqdefault.jpg,2026-04-09 17:08:26.872928
45,9eO-LqtoGps,Jaden Williams,UC78mJyZPMa_OG08KLHjhODw,1.754680e+09,"ChatGPT, hack into the Pentagon #skit #comedy ...",GamerSupps - https://gamersupps.gg/jaden10 (10...,None,https://i.ytimg.com/vi/9eO-LqtoGps/hqdefault.jpg,2026-04-09 17:08:26.872939
46,5jnp86gdQKQ,CarterPCs,UCi7wDE2ZTiR5QYYrUY5WhtA,1.761239e+09,ChatGPT Atlas makes cheating in school too eas...,ChatGPT Atlas makes cheating in school too eas...,None,https://i.ytimg.com/vi/5jnp86gdQKQ/hqdefault.jpg,2026-04-09 17:08:26.872951
47,v2ELPHQF3Lk,Giuliana Mafra,UCcO3pf47GO1rxL4tlWEs5Ow,1.727220e+09,o chat GPT começou uma conversa com um adolesc...,,None,https://i.ytimg.com/vi/v2ELPHQF3Lk/hqdefault.jpg,2026-04-09 17:08:26.872962
48,J_QQ9rCLwSM,Simplilearn,UCsvqVGtbbyHaMoevxPAq9Fg,1.761712e+09,ChatGPT Full Course 2026 | ChatGPT Tutorial Fo...,Professional Certificate in AI and Machine Lea...,None,https://i.ytimg.com/vi/J_QQ9rCLwSM/hqdefault.jpg,2026-04-09 17:08:26.872974
49,zv6I-hO-hOg,rameeen 💋,UCfdot4KXBf7PrapwBGuRpwg,1.748002e+09,never ask ChatGPT this question..,,None,https://i.ytimg.com/vi/zv6I-hO-hOg/hqdefault.jpg,2026-04-09 17:08:26.872986

### 2. Collect a set of comments for the videos from each query

In [14]:
# Retrieve 20 comments from the first video for first query
com = yt.get_video_comments(vids1[0]['video_id'],get_replies = False,max_results = 20)

In [15]:
# Print number of comments collected for first video of first query
len(com)

20

In [16]:
# Retrieve information for the first comment for first video in first query
com[0]

{'video_id': 'Gaf_jCnA6mc',
 'commenter_channel_url': 'http://www.youtube.com/@CharlieChang',
 'commenter_channel_id': 'UCTQuKo8v0PaPCvk5aRxc_Yg',
 'commenter_channel_display_name': '@CharlieChang',
 'comment_id': 'UgxXWftw6OVtb5iFywF4AaABAg',
 'comment_like_count': 716,
 'comment_publish_date': 1680652305.0,
 'text': 'Hope you find this free ChatGPT class helpful! If you guys have any thoughts or questions, I encourage you to use ChatGPT to write a YouTube comment and post it below 😁 And +1 to anyone that uses ChatGPT to create a response to any comments 😎\n\nGet up to 75% off your hosting (only $2.99/mo) + 3 months FREE with Hostinger: \nhttps://www.charliechang.com/hostinger/\n^Use my code CHARLIECHANG for an exclusive discount!\n\nJoin my free AI Community (templates, workflows, AI news, making money with AI, etc): https://www.skool.com/ai-os',
 'commenter_rating': 'none',
 'comment_parent_id': None,
 'collection_date': datetime.datetime(2026, 4, 9, 17, 18, 43, 532333),
 'reply_count': 43}

In [17]:
# Place comment data into a pandas table
com_df = pd.DataFrame(com)

In [18]:
# Extract three columns from pandas table
small_com_df = com_df[['video_id','comment_like_count','text']]

In [19]:
small_com_df

,video_id,comment_like_count,text
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...
3,Gaf_jCnA6mc,0,Thank you very much! 😊
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...
5,Gaf_jCnA6mc,0,Wtf is the point? We have A I now.
6,Gaf_jCnA6mc,0,"Guys, I am the kind of old school programmer t..."
7,Gaf_jCnA6mc,0,Excellent straight-forward information. Thank...
8,Gaf_jCnA6mc,0,Well articulated.
9,Gaf_jCnA6mc,0,❤❤❤❤
10,Gaf_jCnA6mc,0,"The problem with Chat GPT is, takes away our h..."
11,Gaf_jCnA6mc,0,Chat keeps giving the wrong info on creating a...
12,Gaf_jCnA6mc,0,Clean hash fingerprints in Incogniton gave me ...
13,Gaf_jCnA6mc,0,Really neat comprehensive work. Thank you.
14,Gaf_jCnA6mc,0,I want to teach you chat gpt but I will speak ...
15,Gaf_jCnA6mc,1,Super good and very good information and very ...
16,Gaf_jCnA6mc,0,Duck ai is like chat gpt?
17,Gaf_jCnA6mc,0,Who's AI?
18,Gaf_jCnA6mc,1,Do not use this product. They are giving the P...
19,Gaf_jCnA6mc,0,Garbage AI. Too many restrictions. STUPID!

In [21]:
# Print number of rows and columns of pandas table
small_com_df.shape

(20, 3)

In [22]:
# Append the table to itself to test 'concat' function - this should duplicate each row
pd.concat([small_com_df,small_com_df])

,video_id,comment_like_count,text
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...
3,Gaf_jCnA6mc,0,Thank you very much! 😊
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...
5,Gaf_jCnA6mc,0,Wtf is the point? We have A I now.
6,Gaf_jCnA6mc,0,"Guys, I am the kind of old school programmer t..."
7,Gaf_jCnA6mc,0,Excellent straight-forward information. Thank...
8,Gaf_jCnA6mc,0,Well articulated.
9,Gaf_jCnA6mc,0,❤❤❤❤
10,Gaf_jCnA6mc,0,"The problem with Chat GPT is, takes away our h..."
11,Gaf_jCnA6mc,0,Chat keeps giving the wrong info on creating a...
12,Gaf_jCnA6mc,0,Clean hash fingerprints in Incogniton gave me ...
13,Gaf_jCnA6mc,0,Really neat comprehensive work. Thank you.
14,Gaf_jCnA6mc,0,I want to teach you chat gpt but I will speak ...
15,Gaf_jCnA6mc,1,Super good and very good information and very ...
16,Gaf_jCnA6mc,0,Duck ai is like chat gpt?
17,Gaf_jCnA6mc,0,Who's AI?
18,Gaf_jCnA6mc,1,Do not use this product. They are giving the P...
19,Gaf_jCnA6mc,0,Garbage AI. Too many restrictions. STUPID!
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...
3,Gaf_jCnA6mc,0,Thank you very much! 😊
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...
5,Gaf_jCnA6mc,0,Wtf is the point? We have A I now.
6,Gaf_jCnA6mc,0,"Guys, I am the kind of old school programmer t..."
7,Gaf_jCnA6mc,0,Excellent straight-forward information. Thank...
8,Gaf_jCnA6mc,0,Well articulated.
9,Gaf_jCnA6mc,0,❤❤❤❤
10,Gaf_jCnA6mc,0,"The problem with Chat GPT is, takes away our h..."
11,Gaf_jCnA6mc,0,Chat keeps giving the wrong info on creating a...
12,Gaf_jCnA6mc,0,Clean hash fingerprints in Incogniton gave me ...
13,Gaf_jCnA6mc,0,Really neat comprehensive work. Thank you.
14,Gaf_jCnA6mc,0,I want to teach you chat gpt but I will speak ...
15,Gaf_jCnA6mc,1,Super good and very good information and very ...
16,Gaf_jCnA6mc,0,Duck ai is like chat gpt?
17,Gaf_jCnA6mc,0,Who's AI?
18,Gaf_jCnA6mc,1,Do not use this product. They are giving the P...
19,Gaf_jCnA6mc,0,Garbage AI. Too many restrictions. STUPID!

In [23]:
# Define empty table for storing comments from videos in first query
comments1 = pd.DataFrame(columns=['video_id','comment_like_count', 'text'])

In [24]:
# Print empty table
comments1

Empty DataFrame
Columns: [video_id, comment_like_count, text]
Index: []

In [25]:
# Test concat function with the empty table
pd.concat([comments1,small_com_df],ignore_index = True)

,video_id,comment_like_count,text
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...
3,Gaf_jCnA6mc,0,Thank you very much! 😊
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...
5,Gaf_jCnA6mc,0,Wtf is the point? We have A I now.
6,Gaf_jCnA6mc,0,"Guys, I am the kind of old school programmer t..."
7,Gaf_jCnA6mc,0,Excellent straight-forward information. Thank...
8,Gaf_jCnA6mc,0,Well articulated.
9,Gaf_jCnA6mc,0,❤❤❤❤
10,Gaf_jCnA6mc,0,"The problem with Chat GPT is, takes away our h..."
11,Gaf_jCnA6mc,0,Chat keeps giving the wrong info on creating a...
12,Gaf_jCnA6mc,0,Clean hash fingerprints in Incogniton gave me ...
13,Gaf_jCnA6mc,0,Really neat comprehensive work. Thank you.
14,Gaf_jCnA6mc,0,I want to teach you chat gpt but I will speak ...
15,Gaf_jCnA6mc,1,Super good and very good information and very ...
16,Gaf_jCnA6mc,0,Duck ai is like chat gpt?
17,Gaf_jCnA6mc,0,Who's AI?
18,Gaf_jCnA6mc,1,Do not use this product. They are giving the P...
19,Gaf_jCnA6mc,0,Garbage AI. Too many restrictions. STUPID!

In [26]:
# Iterate through videos from first query, pull 20 comments per video, and append them to a single table
for i in vids1:
  try:
    c = yt.get_video_comments(i['video_id'],get_replies = False,max_results = 20)
    cdf = pd.DataFrame(c)
    if cdf.shape[0] > 0:
      scdf = cdf[['video_id','comment_like_count','text']]
      comments1 = pd.concat([comments1,scdf],ignore_index=True)
    print(i['video_id'],'success!',cdf.shape[0])
  except:
    print(i['video_id'],'fail')

Gaf_jCnA6mc success! 20
7zPQV1BSH_k success! 20
l4zRU5n-PNo success! 20
czwzYb-y138 success! 20
loujaeBy8p0 success! 20
hOe0maWOhp8 success! 20
AXn2XVLf7d0 success! 20
JXSm8A-E6gM success! 20
kvU0fe2Ly-s success! 20
qCMVHfIYY7k success! 20
Xm7ySx8VJXo success! 20
1TWpaGgnpjI success! 20
hptchvNnsoI success! 20
XRU-CjzYt_o success! 20
nn29T4yPc8E success! 20
TwPFDbuBLcc success! 20
OxuQrCpMnjI success! 20
HyoQLw8W0lg success! 20
kX_p3r2eLwY success! 20
73ZaWJnrApQ success! 20
zJL9K3xscRo success! 20
tuWg591XYjE success! 20
3jweqQHJ5rg success! 20
WJPDqAzN1X8 success! 20
YAzLh7eOSrk success! 20
VK5mm8JUUJQ success! 20
3aLZ0YwP5so success! 20
3u1k7Jyn434 success! 20
BAfaKsRViZ4 success! 20
cyc1Mr-g6Zk success! 20
ni9-li6IptI success! 20
0rqh5ySV25c success! 20
f2mRAGvKca8 success! 20
vwEFXXajePs success! 20
kHWyJ-baLnE success! 20
GIPlnfHQcz0 success! 20
Zagpt1JHLUI success! 20
4j0Ky_diI44 success! 20
RHRisfGECi0 success! 20
miVkJmaVv-g success! 20
eXA3fVaNuLo success! 17
lycW9qF0lo0 success! 12
n_uCSpQmJkY success! 20
VRjgNgJms3Q success! 20
nlXOQxPP5sQ success! 20
9eO-LqtoGps success! 20
5jnp86gdQKQ success! 20
v2ELPHQF3Lk success! 20
J_QQ9rCLwSM success! 20
zv6I-hO-hOg success! 20

In [27]:
# Define empty table for storing comments from videos in second query
comments2 = pd.DataFrame(columns=['video_id','comment_like_count', 'text'])

In [28]:
# Iterate through videos from second query, pull 20 comments per video, and append them to a single table
for i in vids2:
  try:
    c = yt.get_video_comments(i['video_id'],get_replies = False,max_results = 20)
    cdf = pd.DataFrame(c)
    if cdf.shape[0] > 0:
      scdf = cdf[['video_id','comment_like_count','text']]
      comments2 = pd.concat([comments2,scdf],ignore_index=True)
    print(i['video_id'],'success!',cdf.shape[0])
  except:
    print(i['video_id'],'fail')

L6RBrmYlTAg success! 20
h3AtWdeu_G0 success! 20
t1eHNDB2LOM success! 20
nd_T6hgqFug success! 20
ntDIxaeo3Wg success! 20
We7BZVKbCVw success! 20
0vZ_UVLhSQQ success! 20
DjIG4DIJVS0 success! 20
mZzhfPle9QU success! 20
9FDdQs3AH58 success! 20
brLhhkUqcn4 success! 20
XRU-CjzYt_o success! 20
d8cCSohFcug success! 20
EJyuu6zlQCg success! 20
wfeiCZK0mNs success! 20
rRrBbyv3ChM success! 20
mBHRPeg8zPU success! 20
z9rdrNrkvDY success! 20
GulVqC1ifL0 success! 20
hW4FHg4-Ss0 success! 20
DG1wRgEpdO4 success! 20
OU4gE2M45vY success! 3
mpALXah_PBg success! 20
6q8joS_592k success! 20
s3ccD6m6WKc success! 20
2pM-7fBXc_M success! 20
8xfIarQ9mL0 success! 20
3HVH2Iuplqo success! 20
27Y44JYXZJ8 success! 20
tSOjux2CMM0 success! 20
aFcVKzfkJPk success! 20
dYG8JxtSgmM success! 20
M4cmrdoUKxI success! 20
O2k_qwZA8HU success! 20
Wvj1mTqyzsQ success! 20
5KTHvKCrQ00 success! 20
1Gu3yqDjt3k success! 20
ydCeHVYSvCI success! 20
yV-c7IJjTX8 success! 20
a3uMv1S-1tM success! 20
QoQBzR1NIqI success! 20
1ZN0Zrd9234 success! 20
QbURYdE6ZvU success! 20
ESwH-_xFS_M success! 20
2bsfQThGXxc success! 20
6MBq1paspVU success! 20
6PZCZWvNVHc success! 12
FrAAhSP9hPA success! 20
C9gKWTzRukM success! 20
DW4a1Cm8nG4 success! 20

In [29]:
# Print number of rows and columns of two tables of comments
print("Query 1:",comments1.shape)
print("Query 2:",comments2.shape)

Query 1: (989, 3)
Query 2: (975, 3)

In [30]:
# Print text of first comment from first query
comments1.text[0]

'Hope you find this free ChatGPT class helpful! If you guys have any thoughts or questions, I encourage you to use ChatGPT to write a YouTube comment and post it below 😁 And +1 to anyone that uses ChatGPT to create a response to any comments 😎\n\nGet up to 75% off your hosting (only $2.99/mo) + 3 months FREE with Hostinger: \nhttps://www.charliechang.com/hostinger/\n^Use my code CHARLIECHANG for an exclusive discount!\n\nJoin my free AI Community (templates, workflows, AI news, making money with AI, etc): https://www.skool.com/ai-os'

### 3. Analyze *hatefulness* in the two sets of comments

In [31]:
# Install library for hatefulness analysis https://github.com/pysentimiento/pysentimiento
!pip install pysentimiento

Collecting pysentimiento
  Downloading pysentimiento-0.7.3-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: accelerate>=0.27.2 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (1.13.0)
Requirement already satisfied: datasets>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (4.0.0)
Collecting emoji>=1.6.1 (from pysentimiento)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: spacy>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (3.8.14)
Requirement already satisfied: torch!=2.0.1,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (2.10.0+cpu)
Requirement already satisfied: transformers>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (5.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (1.8.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (2025.3.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (0.24.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (75.2.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch!=2.0.1,>=2.0.0->pysentimiento) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch!=2.0.1,>=2.0.0->pysentimiento) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch!=2.0.1,>=2.0.0->pysentimiento) (3.6.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.13.0->pysentimiento) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.13.0->pysentimiento) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.13.0->pysentimiento) (0.24.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (3.13.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (0.28.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.5.0->pysentimiento) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.5.0->pysentimiento) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.5.0->pysentimiento) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.10.1->pysentimiento) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.10.1->pysentimiento) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.10.1->pysentimiento) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.10.1->pysentimiento) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch!=2.0.1,>=2.0.0->pysentimiento) (1.3.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy>=3.5.0->pysentimiento) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.5.0->pysentimiento) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.5.0->pysentimiento) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy>=3.5.0->pysentimiento) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.10.1->pysentimiento) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.10.1->pysentimiento) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.10.1->pysentimiento) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.10.1->pysentimiento) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy>=3.5.0->pysentimiento) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (0.1.2)
Downloading pysentimiento-0.7.3-py3-none-any.whl (39 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 11.4 MB/s eta 0:00:00
Installing collected packages: emoji, pysentimiento
Successfully installed emoji-2.15.0 pysentimiento-0.7.3

In [32]:
# Import library for text analysis
from pysentimiento import create_analyzer

In [33]:
# Load hatefulness analyzer in English
hate = create_analyzer(task="hate_speech",lang="en")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/980 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pytorch_model.bin:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

In [34]:
# Test hatefulness analyzer on text of first comment
hate.predict(comments1.text[0])

AnalyzerOutput(output=[], probas={hateful: 0.015, targeted: 0.009, aggressive: 0.012})

In [35]:
# Save results of hatefulness analysis of first comment
h = hate.predict(comments1.text[0])

In [36]:
# Print probabilities from hatefulness analysis of first comment
h.probas

{'hateful': 0.015438629314303398,
 'targeted': 0.009295488707721233,
 'aggressive': 0.011547650210559368}

In [37]:
# Print probability of hate in first comment
h.probas['hateful']

0.015438629314303398

In [38]:
# Create empty columns to store probability of hate for all comments
comments1['hateful'] = ''
comments2['hateful'] = ''

In [39]:
# Print table of comments from first query with added column
comments1

,video_id,comment_like_count,text,hateful
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...,
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...,
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...,
3,Gaf_jCnA6mc,0,Thank you very much! 😊,
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...,
...,...,...,...,...
984,zv6I-hO-hOg,0,😂😂😂,
985,zv6I-hO-hOg,0,🙂🙂🙂,
986,zv6I-hO-hOg,0,How ur chatgpt giving answers like this,
987,zv6I-hO-hOg,1,nahhh getting doxxed AI is WILD💀🥀,
988,zv6I-hO-hOg,0,Once i was using mic to type my sentence and i...,

In [40]:
# Iterate through comments of first query, analyze for hatefulness, then place scores in the table
# NOTE: this may take several minutes to complete
for index,row in comments1.iterrows():
  h = hate.predict(row['text'])
  comments1.at[index, 'hateful'] = h.probas['hateful']
  if((index + 1) % 50 == 0):
    print(index + 1,end=" ")

50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950

In [41]:
# Print comments and hatefulness probabilities for first query
comments1

,video_id,comment_like_count,text,hateful
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...,0.015439
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...,0.016488
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...,0.017435
3,Gaf_jCnA6mc,0,Thank you very much! 😊,0.014731
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...,0.018351
...,...,...,...,...
984,zv6I-hO-hOg,0,😂😂😂,0.015362
985,zv6I-hO-hOg,0,🙂🙂🙂,0.016874
986,zv6I-hO-hOg,0,How ur chatgpt giving answers like this,0.015799
987,zv6I-hO-hOg,1,nahhh getting doxxed AI is WILD💀🥀,0.026578
988,zv6I-hO-hOg,0,Once i was using mic to type my sentence and i...,0.052631

In [42]:
# Iterate through comments of second query, analyze for hatefulness, then place scores in the table
# NOTE: this may take several minutes to complete
for index,row in comments2.iterrows():
  h = hate.predict(row['text'])
  comments2.at[index, 'hateful'] = h.probas['hateful']
  if((index + 1) % 50 == 0):
    print(index + 1,end=" ")

50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950

In [43]:
# Print comments and hatefulness probabilities for second query
comments2

,video_id,comment_like_count,text,hateful
0,L6RBrmYlTAg,0,"awesome, you know Claude should be paying you ...",0.016499
1,L6RBrmYlTAg,0,I love Claude.. huge difference from others AI...,0.014755
2,L6RBrmYlTAg,0,The video tutorial is improving with slower sp...,0.015263
3,L6RBrmYlTAg,0,a lot of these use cases point to the same shi...,0.016527
4,L6RBrmYlTAg,0,"Hey, why are you rushing the horses like that?...",0.028015
...,...,...,...,...
970,DW4a1Cm8nG4,0,Claude cowork is paid ?,0.01737
971,DW4a1Cm8nG4,0,"Greg, don’t do other stuff during an interview...",0.01787
972,DW4a1Cm8nG4,1,Best episode ever🎉🎉,0.016929
973,DW4a1Cm8nG4,0,I don’t know anything about any of this stuff ...,0.01559
974,DW4a1Cm8nG4,0,Just reduce the volume of the intro music sect...,0.02539

### 4. Compare the average hatefulness in the two sets *(descriptive norm)*

In [44]:
# Create columns to store indicator for first/second query
comments1['query'] = 0
comments2['query'] = 1

In [45]:
# Append the two tables together
all = pd.concat([comments1,comments2],ignore_index = True)

In [46]:
# Print table of comments
all

,video_id,comment_like_count,text,hateful,query
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...,0.015439,0
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...,0.016488,0
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...,0.017435,0
3,Gaf_jCnA6mc,0,Thank you very much! 😊,0.014731,0
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...,0.018351,0
...,...,...,...,...,...
1959,DW4a1Cm8nG4,0,Claude cowork is paid ?,0.01737,1
1960,DW4a1Cm8nG4,0,"Greg, don’t do other stuff during an interview...",0.01787,1
1961,DW4a1Cm8nG4,1,Best episode ever🎉🎉,0.016929,1
1962,DW4a1Cm8nG4,0,I don’t know anything about any of this stuff ...,0.01559,1
1963,DW4a1Cm8nG4,0,Just reduce the volume of the intro music sect...,0.02539,1

In [47]:
# Print variable types
all.dtypes

video_id              object
comment_like_count    object
text                  object
hateful               object
query                  int64
dtype: object

In [48]:
# Convert variable types to numbers
all['comment_like_count'] = all['comment_like_count'].astype(int)
all['hateful'] = all['hateful'].astype(float)

In [49]:
# Print variable types after changes
all.dtypes

video_id               object
comment_like_count      int64
text                   object
hateful               float64
query                   int64
dtype: object

In [50]:
# Create binary variable capturing if probability of hatefulness > 50%
all['hate_thresh'] = all['hateful'].apply(lambda x: 1 if x > .5 else 0)

In [51]:
# Print number of columns where probability of hatefulness > 50%
all.loc[all['hate_thresh'] == 1].size

48

In [52]:
# Create column of all 1s to add a constant to the models
all['constant'] = 1

In [53]:
# Print table with all of the created variables
all

,video_id,comment_like_count,text,hateful,query,hate_thresh,constant
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...,0.015439,0,0,1
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...,0.016488,0,0,1
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...,0.017435,0,0,1
3,Gaf_jCnA6mc,0,Thank you very much! 😊,0.014731,0,0,1
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...,0.018351,0,0,1
...,...,...,...,...,...,...,...
1959,DW4a1Cm8nG4,0,Claude cowork is paid ?,0.017370,1,0,1
1960,DW4a1Cm8nG4,0,"Greg, don’t do other stuff during an interview...",0.017870,1,0,1
1961,DW4a1Cm8nG4,1,Best episode ever🎉🎉,0.016929,1,0,1
1962,DW4a1Cm8nG4,0,I don’t know anything about any of this stuff ...,0.015590,1,0,1
1963,DW4a1Cm8nG4,0,Just reduce the volume of the intro music sect...,0.025390,1,0,1

In [54]:
# Model the difference in hate probability across the two queries using OLS regression
model1 = sm.OLS(all['hateful'],all[['query','constant']])

In [55]:
# Print Model 1 results
model1.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                hateful   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.005
Method:                 Least Squares   F-statistic:                     11.73
Date:                Thu, 09 Apr 2026   Prob (F-statistic):           0.000628
Time:                        17:58:31   Log-Likelihood:                 3120.1
No. Observations:                1964   AIC:                            -6236.
Df Residuals:                    1962   BIC:                            -6225.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
query         -0.0076      0.002     -3.425      0.001      -0.012      -0.003
constant       0.0285      0.002     18.102      0.000       0.025       0.032
==============================================================================
Omnibus:                     3650.186   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          3630310.112
Skew:                          13.775   Prob(JB):                         0.00
Kurtosis:                     211.814   Cond. No.                         2.61
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [56]:
# Model the difference in hate prevalence across the two queries using OLS regression
model2 = sm.OLS(all['hate_thresh'],all[['query','constant']])

In [57]:
# Print Model 2 results
model2.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            hate_thresh   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     4.439
Date:                Thu, 09 Apr 2026   Prob (F-statistic):             0.0353
Time:                        17:58:37   Log-Likelihood:                 2623.7
No. Observations:                1964   AIC:                            -5243.
Df Residuals:                    1962   BIC:                            -5232.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
query         -0.0061      0.003     -2.107      0.035      -0.012      -0.000
constant       0.0071      0.002      3.497      0.000       0.003       0.011
==============================================================================
Omnibus:                     3857.760   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          4769373.853
Skew:                          15.520   Prob(JB):                         0.00
Kurtosis:                     242.412   Cond. No.                         2.61
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [58]:
# Model the difference in hate prevalence across the two queries using Logit regression
model3 = sm.GLM(all['hate_thresh'],all[['query','constant']],family=sm.families.Binomial())

In [59]:
# Print Model 3 results
model3.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:            hate_thresh   No. Observations:                 1964
Model:                            GLM   Df Residuals:                     1962
Model Family:                Binomial   Df Model:                            1
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -49.513
Date:                Thu, 09 Apr 2026   Deviance:                       99.025
Time:                        17:58:41   Pearson chi2:                 1.96e+03
No. Iterations:                    10   Pseudo R-squ. (CS):           0.002540
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
query         -1.9377      1.070     -1.811      0.070      -4.035       0.159
constant      -4.9437      0.379    -13.033      0.000      -5.687      -4.200
==============================================================================
"""

### 5. Compare association between hatefulness and likes in the two sets *(injunctive norm)*

In [60]:
# Create columns capturing the interaction between query and hatefulness
all['interaction'] = all['query']*all['hateful']
all['int_thresh'] = all['query']*all['hate_thresh']

In [61]:
# Print updated table with all variables
all

,video_id,comment_like_count,text,hateful,query,hate_thresh,constant,interaction,int_thresh
0,Gaf_jCnA6mc,716,Hope you find this free ChatGPT class helpful!...,0.015439,0,0,1,0.000000,0
1,Gaf_jCnA6mc,0,Can you make an update It looks like from anot...,0.016488,0,0,1,0.000000,0
2,Gaf_jCnA6mc,0,The craziest part about this is that you have ...,0.017435,0,0,1,0.000000,0
3,Gaf_jCnA6mc,0,Thank you very much! 😊,0.014731,0,0,1,0.000000,0
4,Gaf_jCnA6mc,0,Your avances en tecnología is making the Kids ...,0.018351,0,0,1,0.000000,0
...,...,...,...,...,...,...,...,...,...
1959,DW4a1Cm8nG4,0,Claude cowork is paid ?,0.017370,1,0,1,0.017370,0
1960,DW4a1Cm8nG4,0,"Greg, don’t do other stuff during an interview...",0.017870,1,0,1,0.017870,0
1961,DW4a1Cm8nG4,1,Best episode ever🎉🎉,0.016929,1,0,1,0.016929,0
1962,DW4a1Cm8nG4,0,I don’t know anything about any of this stuff ...,0.015590,1,0,1,0.015590,0
1963,DW4a1Cm8nG4,0,Just reduce the volume of the intro music sect...,0.025390,1,0,1,0.025390,0

In [62]:
# Model associating hate probability and likes across the two queries using OLS
model4 = sm.OLS(all['comment_like_count'],all[['query','hateful','interaction','constant']])

In [63]:
# Print Model 4 results
model4.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:     comment_like_count   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.3987
Date:                Thu, 09 Apr 2026   Prob (F-statistic):              0.754
Time:                        17:58:49   Log-Likelihood:                -16091.
No. Observations:                1964   AIC:                         3.219e+04
Df Residuals:                    1960   BIC:                         3.221e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
query         -45.1537     46.281     -0.976      0.329    -135.920      45.612
hateful      -125.0325    437.223     -0.286      0.775    -982.503     732.438
interaction   119.0050   1082.493      0.110      0.912   -2003.953    2241.963
constant       46.4679     30.502      1.523      0.128     -13.352     106.288
==============================================================================
Omnibus:                     5991.482   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        308965256.127
Skew:                          43.989   Prob(JB):                         0.00
Kurtosis:                    1944.083   Cond. No.                         63.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [64]:
# Model associating hate prevalence and likes across the two queries using OLS
model5 = sm.OLS(all['comment_like_count'],all[['query','hate_thresh','int_thresh','constant']])

In [65]:
# Print Model 5 results
model5.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:     comment_like_count   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.3770
Date:                Thu, 09 Apr 2026   Prob (F-statistic):              0.770
Time:                        17:58:53   Log-Likelihood:                -16091.
No. Observations:                1964   AIC:                         3.219e+04
Df Residuals:                    1960   BIC:                         3.221e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
query         -42.0249     39.607     -1.061      0.289    -119.702      35.652
hate_thresh   -43.0720    332.214     -0.130      0.897    -694.602     608.458
int_thresh     41.8821    937.149      0.045      0.964   -1796.031    1879.796
constant       43.2149     27.949      1.546      0.122     -11.598      98.028
==============================================================================
Omnibus:                     5991.570   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        308998550.611
Skew:                          43.990   Prob(JB):                         0.00
Kurtosis:                    1944.188   Cond. No.                         54.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [66]:
# Model associating hate probability and likes across the two queries using Negative Binomial
model6 = sm.GLM(all['comment_like_count'],all[['query','hateful','interaction','constant']],family=sm.families.NegativeBinomial())

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

In [67]:
# Print Model 6 results
model6.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:     comment_like_count   No. Observations:                 1964
Model:                            GLM   Df Residuals:                     1960
Model Family:        NegativeBinomial   Df Model:                            3
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -5529.8
Date:                Thu, 09 Apr 2026   Deviance:                       9690.1
Time:                        17:58:57   Pearson chi2:                 4.50e+15
No. Iterations:                    41   Pseudo R-squ. (CS):             0.9267
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
query          -6.4567      0.331    -19.483      0.000      -7.106      -5.807
hateful      -313.1769      9.739    -32.157      0.000    -332.265    -294.089
interaction   168.2974     18.540      9.078      0.000     131.960     204.635
constant        9.1670      0.182     50.273      0.000       8.810       9.524
===============================================================================
"""

In [68]:
# Model associating hate prevalence and likes across the two queries using Negative Binomial
model7 = sm.GLM(all['comment_like_count'],all[['query','hate_thresh','int_thresh','constant']],family=sm.families.NegativeBinomial())

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

In [69]:
# Print Model 7 results
model7.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:     comment_like_count   No. Observations:                 1964
Model:                            GLM   Df Residuals:                     1960
Model Family:        NegativeBinomial   Df Model:                            3
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -6165.1
Date:                Thu, 09 Apr 2026   Deviance:                       10961.
Time:                        17:59:01   Pearson chi2:                 8.18e+05
No. Iterations:                    23   Pseudo R-squ. (CS):             0.8600
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
query          -3.5923      0.054    -66.349      0.000      -3.698      -3.486
hate_thresh    -5.7121      1.070     -5.341      0.000      -7.808      -3.616
int_thresh    -15.0549    1.8e+04     -0.001      0.999   -3.52e+04    3.52e+04
constant        3.7662      0.032    116.678      0.000       3.703       3.829
===============================================================================
"""